# Generated by Django 3.0.4 on 2020-03-24 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200313_0040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
