# Generated by Django 3.0.4 on 2020-04-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20200410_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='created',
            new_name='time_created',
        ),
    ]
