# Generated by Django 3.0.4 on 2020-04-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20200410_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
