# Generated by Django 3.0.4 on 2020-04-14 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20200412_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='img',
            field=models.ImageField(default='myproj/static_env/static_root/images/aws.jpg', upload_to='myproj/static_env/media_root'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 13, 35, 22, 649271)),
        ),
    ]
