# Generated by Django 3.0.4 on 2020-04-14 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_auto_20200414_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='active',
        ),
        migrations.AlterField(
            model_name='posts',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 17, 7, 12, 452597)),
        ),
    ]
