# Generated by Django 3.0.4 on 2020-04-14 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_auto_20200414_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='img',
            field=models.ImageField(default='myproj/static_env/static_root/images/aws.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='posts',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 17, 19, 25, 431300)),
        ),
    ]
