# Generated by Django 3.0.4 on 2020-04-15 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_auto_20200415_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 11, 30, 16, 548704)),
        ),
    ]
