# Generated by Django 3.0.4 on 2020-04-15 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0021_auto_20200415_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='tags',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 17, 29, 56, 965216)),
        ),
    ]
