# Generated by Django 3.0.4 on 2020-04-21 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0027_auto_20200421_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 13, 47, 57, 205311)),
        ),
    ]
